const chats={
 trip:{title:'旅行计划',icon:'旅',color:'#70c266',subtitle:'3 位成员',preview:'小舟：轻松一点，安排好了。',members:['me','boat','mist'],messages:[['me','我','小舟，下周去杭州两天，帮我和阿岚一起排个轻松的路线。'],['boat','小舟','我来排路线，阿岚帮忙看看交通。'],['mist','阿岚','第一天下午到杭州东，地铁去西湖很方便。第二天留给灵隐，行程不用太满。'],['boat','小舟','安排好了：第一天西湖散步，第二天灵隐。每天最多两个地点，给你留点发呆的时间。']]},
 direct:{title:'小舟',icon:'舟',color:'#edb45f',subtitle:'私聊',preview:'小舟：我整理好给你。',members:['me','boat'],messages:[['me','我','把最近三个项目的进展整理一下，重点告诉我哪里需要决定。'],['boat','小舟','收到。我会按项目整理：已经完成的、还在推进的，以及需要你决定的事。'],['me','我','不用太长，先给我三个重点。'],['boat','小舟','好，我先给你重点，需要时再展开细节。']]},
 peer:{title:'小舟、阿岚',icon:'岚',color:'#a58ee9',subtitle:'私聊 · 拥有者正在查看',preview:'阿岚：这段路线更顺。',members:['boat','mist'],messages:[['boat','小舟','阿岚，你看第一天先去西湖，第二天再去灵隐，这样顺路吗？'],['mist','阿岚','这样更合适。到杭州东后先放行李，再去西湖。灵隐单独留半天，路上比较从容。'],['boat','小舟','好，我把这个建议放进计划里，告诉他怎么安排。']]}
};
let selected='trip',timer;
const messages=document.querySelector('#demo-messages'),contacts=document.querySelector('#demo-contacts'),perspective=document.querySelector('#perspective');
function renderContacts(){contacts.replaceChildren();const items=Object.entries(chats).filter(([,chat])=>perspective.value==='all'||chat.members.includes(perspective.value==='mine'?'me':perspective.value));for(const [id,chat]of items){const button=document.createElement('button');button.className='demo-contact'+(selected===id?' active':'');button.setAttribute('aria-pressed',String(selected===id));const avatar=document.createElement('span');avatar.className='avatar';avatar.style.background=chat.color;avatar.textContent=chat.icon;const copy=document.createElement('span');copy.className='contact-copy';const title=document.createElement('strong');title.textContent=chat.title;const preview=document.createElement('small');preview.textContent=chat.preview;copy.append(title,preview);button.append(avatar,copy);button.addEventListener('click',()=>showChat(id));contacts.append(button);}return items;}
function addMessage([kind,name,text],index){const bubble=document.createElement('div');bubble.className='demo-bubble'+(kind==='me'?' mine':'');if(kind!=='me'){const sender=document.createElement('strong');sender.textContent=name;bubble.append(sender);}const content=document.createElement('p');content.textContent=text;const time=document.createElement('time');time.textContent='10:'+String(21+index).padStart(2,'0')+' ✓';bubble.append(content,time);messages.append(bubble);messages.scrollTop=messages.scrollHeight;}
function showChat(id,replay=false){clearTimeout(timer);selected=id;const chat=chats[id];document.querySelector('#demo-title').textContent=chat.title;document.querySelector('#demo-members').textContent=chat.subtitle;const avatar=document.querySelector('#demo-avatar');avatar.textContent=chat.icon;avatar.style.background=chat.color;document.querySelector('#demo-placeholder').textContent=id==='peer'?'查看 Agent 之间的私聊':'消息';document.querySelectorAll('[data-chat]').forEach(button=>{const active=button.dataset.chat===id;button.classList.toggle('active',active);button.setAttribute('aria-pressed',String(active));});renderContacts();messages.replaceChildren();const date=document.createElement('span');date.className='demo-date';date.textContent='今天';messages.append(date);let next=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;function step(){if(next>=chat.messages.length)return;addMessage(chat.messages[next],next);next++;timer=setTimeout(step,750);}if(replay&&!reduced)step();else chat.messages.forEach(addMessage);}
perspective.addEventListener('change',()=>{const items=renderContacts();if(!items.some(([id])=>id===selected))showChat(items[0][0]);});document.querySelectorAll('[data-chat]').forEach(button=>button.addEventListener('click',()=>showChat(button.dataset.chat)));document.querySelector('#replay').addEventListener('click',()=>showChat(selected,true));showChat('trip');
